import type { Metadata } from "next";// Next.jsのメタデータの型をインポート
import { Geist, Geist_Mono } from "next/font/google";// Google FontsのGeistとGeist Monoをインポート
import "./globals.css";// グローバルなCSSファイルをインポート

const geistSans = Geist({// Geistフォントの設定
  variable: "--font-geist-sans",// CSS変数名を指定
  subsets: ["latin"],// ラテン文字のサブセットを指定
});

const geistMono = Geist_Mono({// Geist Monoフォントの設定
  variable: "--font-geist-mono",// CSS変数名を指定
  subsets: ["latin"],// ラテン文字のサブセットを指定
});

export const metadata: Metadata = {// ページのメタデータを定義
  title: "Create Next App",// ページのタイトル
  description: "Generated by create next app",// ページの説明
};

export default function RootLayout({// ルートレイアウトコンポーネント。全てのページで共通のレイアウトを定義するためのコンポーネント
  children,// 子コンポーネントを受け取るためのprops
}: Readonly<{// propsの型を定義
  children: React.ReactNode;// childrenはReactのノード（要素、文字列、フラグメントなど）であることを指定
}>) {
  return (
    <html lang="en">//
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}// フォントのCSS変数をクラスに追加して、全体で使用できるようにする。antialiasedはテキストのアンチエイリアスを有効にするクラス
      >
        {children}
      </body>
    </html>
  );
}
